apiVersion: apps/v1
kind: Deployment
metadata:
    name: wil-playground
    labels:
        app.kubernetes.io/name: playground
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: playground
    template:
        metadata:
            labels:
                app.kubernetes.io/name: playground
        spec:
            containers:
                - name: playground
                  image: wil42/playground:v2
                  ports:
                    - containerPort: 8888
                      name: http-app-svc
