apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app_name }}-svc
spec:
    selector:
        app.kubernetes.io/name: {{ .Values.app_label }}
    ports:
        - name: {{ .Values.servicePort.name }}
          protocol: TCP
          port: {{ .Values.servicePort.number }}
          targetPort: {{ .Values.container.port.name }}
